minecraft_dependency=1.20.1
minecraft_version=1.20.1

# https://fabricmc.net/develop/
fabric_version=0.92.0+1.20.1

# https://modrinth.com/mod/malilib
# https://modrinth.com/mod/tweakeroo
# https://modrinth.com/mod/litematica
# https://jitpack.io/#sakura-ryoko/malilib
# https://jitpack.io/#sakura-ryoko/tweakeroo
# https://jitpack.io/#sakura-ryoko/litematica
malilib=0.16.3
litematica=0.15.4
tweakeroo=0.17.1

#https://modrinth.com/mod/modmenu/versions
modmenu=7.2.2

#https://www.curseforge.com/minecraft/mc-mods/quick-shulker/files/all
quick_shulker=4592296
kyrptconfig=1.5.4-1.20

#https://modrinth.com/mod/chest-tracker/versions
#https://modrinth.com/mod/where-is-it/versions?l=fabric
#https://maven.jackf.red/#/releases/red/jackf/jackfredlib/jackfredlib
#https://modrinth.com/mod/searchables/versions?l=fabric
#https://maven.isxander.dev/#/releases/dev/isxander/yacl/yet-another-config-lib-fabric
chesttracker=2.6.3+1.20.1
whereisit=2.4.1+1.20.1
jackfredlib=0.10.5+1.20.1
searchables=Searchables-fabric-1.20.1:1.0.2
yacl=3.6.1+1.20.1-fabric