minecraft_dependency=1.19.4
minecraft_version=1.19.4

# https://fabricmc.net/develop/
fabric_version=0.87.2+1.19.4

# https://modrinth.com/mod/malilib
# https://modrinth.com/mod/tweakeroo
# https://modrinth.com/mod/litematica
# https://jitpack.io/#sakura-ryoko/malilib
# https://jitpack.io/#sakura-ryoko/tweakeroo
# https://jitpack.io/#sakura-ryoko/litematica
malilib=0.15.4
litematica=0.14.7
tweakeroo=0.16.0

# https://modrinth.com/mod/modmenu/versions
modmenu=6.3.1

# https://www.curseforge.com/minecraft/mc-mods/quick-shulker/files/all
quick_shulker=4592290
kyrptconfig=1.5.2-1.19.4

# https://modrinth.com/mod/chest-tracker/versions
# https://modrinth.com/mod/where-is-it/versions?l=fabric
# https://modrinth.com/mod/cloth-config/versions?l=fabric
# https://github.com/CottonMC/LibGui/releases
chesttracker=1.1.21
whereisit=1.14.16
cloth_config=10.1.135
LibGui=7.1.1+1.19.4

