minecraft_dependency=>=26.1 <=26.1.2
minecraft_version=26.1

# https://fabricmc.net/develop/
fabric_version=0.144.3+26.1

# https://modrinth.com/mod/malilib
# https://modrinth.com/mod/malilib
# https://modrinth.com/mod/tweakeroo
# https://modrinth.com/mod/litematica
# https://jitpack.io/#sakura-ryoko/malilib
# https://jitpack.io/#sakura-ryoko/tweakeroo
# https://jitpack.io/#sakura-ryoko/litematica
malilib=0.28.9
litematica=0.27.10
tweakeroo=0.28.6

# https://modrinth.com/mod/modmenu/versions
# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
modmenu=18.0.0

quickshulker=https://github.com/EnderPhantomWing/quickshulker-multi/releases/download/3.2.2/quickshulker-v3.2.2-mc26.1.jar

# https://modrinth.com/mod/chest-tracker-port/versions
chesttracker=2.8.2+26.1

# https://modrinth.com/mod/where-is-it-port/version
whereisit=2.7.5+26.1

# https://maven.jackf.red/#/releases/red/jackf/jackfredlib/jackfredlib
jackfredlib=0.10.6-26.1

# https://maven.blamejared.com/com/blamejared/searchables/
searchables=Searchables-fabric-26.1:1.0.4

# https://modrinth.com/mod/yacl/versions?l=fabric
yacl=3.9.1+26.1-fabric