minecraft_dependency=1.20.6
minecraft_version=1.20.6

# https://fabricmc.net/develop/
fabric_version=0.99.4+1.20.6

# https://modrinth.com/mod/malilib
# https://modrinth.com/mod/tweakeroo
# https://modrinth.com/mod/litematica
# https://jitpack.io/#sakura-ryoko/malilib
# https://jitpack.io/#sakura-ryoko/tweakeroo
# https://jitpack.io/#sakura-ryoko/litematica
malilib=0.19.2
litematica=0.18.3
tweakeroo=0.20.0

# https://modrinth.com/mod/modmenu/versions
modmenu=10.0.0

# https://www.curseforge.com/minecraft/mc-mods/quick-shulker/files/all
quickshulker=https://github.com/Haocen2004/quickshulker/releases/download/1.20.6-1.4.3/quickshulker-1.4.3-1.20.6.jar
kyrptconfig=1.5.4-1.20

# https://modrinth.com/mod/chest-tracker/versions
# https://modrinth.com/mod/where-is-it/versions?l=fabric
# https://maven.jackf.red/#/releases/red/jackf/jackfredlib/jackfredlib
# https://modrinth.com/mod/searchables/versions?l=fabric
# https://modrinth.com/mod/yacl/versions?l=fabric

chesttracker=2.4.12+1.20.6
whereisit=2.4.3+1.20.6
jackfredlib=0.10.2+1.20.6
searchables=Searchables-fabric-1.20.6:1.0.1
yacl=3.4.4+1.20.6-fabric