minecraft_dependency=>=26.2
minecraft_version=26.2

# https://fabricmc.net/develop/
fabric_version=0.152.2+26.2


# https://modrinth.com/mod/malilib
# https://modrinth.com/mod/litematica
# https://modrinth.com/mod/tweakeroo
malilib=0.29.0
litematica=0.28.0
tweakeroo=0.29.0

# https://modrinth.com/mod/modmenu/versions
modmenu=20.0.0-beta.3

quickshulker=https://github.com/EnderPhantomWing/quickshulker-multi/releases/download/3.2.5/quickshulker-v3.2.5-mc26.2-a7aa281-release.jar

# https://modrinth.com/mod/chest-tracker-port/versions
chesttracker=2.8.2+26.1.2

# https://modrinth.com/mod/where-is-it-port/versions
whereisit=2.7.5+26.1

# https://maven.jackf.red/#/releases/red/jackf/jackfredlib/jackfredlib
jackfredlib=0.10.6-26.1

# https://maven.blamejared.com/com/blamejared/searchables/
searchables=Searchables-fabric-26.2:1.0.1

# https://modrinth.com/mod/yacl/versions?l=fabric
yacl=3.9.4+26.2-fabric