minecraft_dependency=1.18.2
minecraft_version=1.18.2

# https://fabricmc.net/develop/
fabric_version=0.77.0+1.18.2

# https://modrinth.com/mod/malilib
# https://modrinth.com/mod/tweakeroo
# https://modrinth.com/mod/litematica
# https://jitpack.io/#sakura-ryoko/malilib
# https://jitpack.io/#sakura-ryoko/tweakeroo
# https://jitpack.io/#sakura-ryoko/litematica
malilib=0.12.1
litematica=0.11.7
tweakeroo=0.13.3

#https://modrinth.com/mod/modmenu/versions
modmenu=3.2.5

# https://www.curseforge.com/minecraft/mc-mods/quick-shulker/files/all
# https://github.com/CottonMC/LibGui/releases
quick_shulker=4008786
kyrptconfig=1.4.6-1.18

# https://modrinth.com/mod/chest-tracker/versions
# https://modrinth.com/mod/where-is-it/versions?l=fabric
# https://modrinth.com/mod/cloth-config/versions?l=fabric
# https://www.curseforge.com/minecraft/mc-mods/cloth-api/files/all
chesttracker=1.1.16
LibGui=5.4.1+1.18.2
whereisit=1.14.10
cloth_config=6.5.133
cloth_api=3.2.64
