minecraft_dependency=1.20.2
minecraft_version=1.20.2

# https://fabricmc.net/develop/
fabric_version=0.91.6+1.20.2

# https://modrinth.com/mod/malilib
# https://modrinth.com/mod/tweakeroo
# https://modrinth.com/mod/litematica
# https://jitpack.io/#sakura-ryoko/malilib
# https://jitpack.io/#sakura-ryoko/tweakeroo
# https://jitpack.io/#sakura-ryoko/litematica
malilib=0.18.3
litematica=0.17.4
tweakeroo=0.19.4

# https://modrinth.com/mod/modmenu/versions
modmenu=8.0.1

# https://www.curseforge.com/minecraft/mc-mods/quick-shulker/files/all
quick_shulker=4592296
kyrptconfig=1.5.4-1.20

# https://modrinth.com/mod/chest-tracker/versions
# https://modrinth.com/mod/where-is-it/versions?l=fabric
# https://maven.jackf.red/#/releases/red/jackf/jackfredlib/jackfredlib
# https://modrinth.com/mod/searchables/versions?l=fabric
# https://maven.isxander.dev/#/snapshots/dev/isxander/yet-another-config-lib
chesttracker=2.4.12+1.20.2
whereisit=2.4.3+1.20.2
jackfredlib=0.10.2+1.20.2
searchables=Searchables-fabric-1.20.2:1.0.16
yacl=3.6.1+1.20.1-fabric

