minecraft_dependency=>=1.21.6 <=1.21.8
minecraft_version=1.21.6

# https://fabricmc.net/develop/
fabric_version=0.128.1+1.21.6

# https://modrinth.com/mod/malilib
# https://modrinth.com/mod/malilib
# https://modrinth.com/mod/tweakeroo
# https://modrinth.com/mod/litematica
# https://jitpack.io/#sakura-ryoko/malilib
# https://jitpack.io/#sakura-ryoko/tweakeroo
# https://jitpack.io/#sakura-ryoko/litematica
malilib=0.25.7
litematica=0.23.7
tweakeroo=0.25.6

# https://modrinth.com/mod/modmenu/versions
modmenu=15.0.2

quickshulker=https://github.com/MoRanpcy/quickshulker/releases/download/2.5.2-1.21.6/quickshulker-2.5.2-1.21.6.jar

# https://modrinth.com/mod/chest-tracker-port/versions
# https://maven.jackf.red/#/releases/red/jackf/jackfredlib/jackfredlib
# https://maven.blamejared.com/com/blamejared/searchables/
# https://modrinth.com/mod/searchables/versions?l=fabric
# https://modrinth.com/mod/yacl/versions?l=fabric
chesttracker=2.8.2+1.21.6
whereisit=2.7.1+1.21.6
jackfredlib=0.10.6-1.21.6
searchables=Searchables-fabric-1.21.6:1.0.2
yacl=3.7.1+1.21.6-fabric
