name: _step.release_build
on:
  workflow_call:
    inputs:
      release:
        type: boolean
        required: false
        default: false
      target_subproject:
        description: see release.yml, leave it empty to build all
        type: string
        required: false
        default: ''
  workflow_dispatch: 

env:
  IS_THIS_RELEASE: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'SKIP') }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Cache Gradle dependencies (公共缓存)
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle
          # 固定缓存键（公共缓存），不依赖文件哈希
          key: ${{ runner.os }}-gradle-common
          # 恢复键与主键一致，确保优先使用公共缓存
          restore-keys: |
            ${{ runner.os }}-gradle-common

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build (多版本模组包)
        run: ./gradlew :fabricWrapper:build --stacktrace

      - name: Delete versionpack-sources.jar
        run: |
          find fabricWrapper/build/libs/ -name "*-sources.jar" -exec rm {} \;

      - name: Upload versionpack jar
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: fabricWrapper/build/libs/

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: fabricWrapper/build/libs/*
          token: ${{ secrets.GITHUB_TOKEN }}
